# Generated by Django 3.2.9 on 2021-11-14 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetMedical', '0002_book_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('arrived ', 'arrived '), ('lost ', 'lost '), ('did_not_arrive ', 'did_not_arrive ')], max_length=50, null=True)),
                ('books', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinetMedical.book')),
                ('projet1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinetMedical.projet1')),
                ('tags', models.ManyToManyField(to='cabinetMedical.Tag')),
            ],
        ),
    ]
