# Generated by Django 3.2.9 on 2021-11-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetMedical', '0003_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projet1',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='projet1',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='projet1',
            new_name='client',
        ),
    ]
